# Generated by Django 3.0.6 on 2020-05-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200524_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publicationdate',
        ),
        migrations.AddField(
            model_name='article',
            name='publicationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
