# Generated by Django 3.0.6 on 2020-05-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200524_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publicationDate',
            new_name='publicationdate',
        ),
    ]
