# Generated by Django 3.0.5 on 2020-05-25 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_auto_20200524_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publicationdate',
            new_name='publication_date',
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Article')),
            ],
        ),
    ]
