news_sites:
    eluniversal:
        url: https://www.eluniversal.com.mx
        queries: 
            homepage_article_links: '.field-content a'
            article_body: '.field-name-body'
            article_title: '.pane-content h1'
    elespectador: 
        url: https://www.elespectador.com
        queries:
            homepage_article_links: '.node-title a'
            article_body: '.node-body'
            article_title: '.node-title'
    diariodecuba:
        url: https://diariodecuba.com
        queries:
            homepage_article_links: '.views-title-section a'
            article_body: '.content'
            article_title: '.article-title'

           