version: '3'

services:
  web:
    build:
      command: python /src/manage.py runserver 127.0.0.1:5000
      volumes: 
      -  :/src
      ports: 
       - "5000:5000"
      depends_on:
       - db

  db:
    image: postgres
